### ISSUE TITLE
codedump assertion failure error

### ISSUE THREAD

**Issue by Ruturaj4** [mxz297/dyninst-tools#1]
Hi,

Thanks so much for the tools. I am getting following error when I try to run codedump:

```
[r668v698@themata CodeDump]$ ./CodeDump /projects/zephyr/Ruturaj/re_challenges/type_inference/bytewrite-1
CodeDump: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)
```

**Comment by mxz297** [comment]
It looks like this is a memory corruption as it is asserting inside malloc. Can you run valgrind to see what's going on? In addition, can you provide more information about your operation system, compiler, and the dyninst version you are using?

**Comment by Ruturaj4** [comment]
Actually I figured it out. Environment variable was not set. Thanks btw for you quick reply. :-)
